# Generated by Django 3.2.8 on 2022-01-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, null=True)),
                ('surname', models.CharField(max_length=190, null=True)),
                ('email', models.CharField(max_length=190, null=True)),
                ('phone', models.CharField(max_length=190, null=True)),
                ('collegelevel', models.CharField(choices=[('1CPI', '1CPI'), ('2CPI', '2CPI'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], max_length=4)),
                ('datebirth', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
