# Generated by Django 3.2.8 on 2022-01-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0003_auto_20220104_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='userimg.png', upload_to=''),
        ),
    ]
