# Generated by Django 3.2.8 on 2022-01-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0007_auto_20220104_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='https://cdn-icons-png.flaticon.com/128/1946/1946429.png', null=True, upload_to=''),
        ),
    ]
