# Generated by Django 3.2.8 on 2022-01-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0012_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='images/user.png', null=True, upload_to='images/'),
        ),
    ]
