# Generated by Django 3.2.8 on 2022-01-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0013_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='collegelevel',
            field=models.CharField(choices=[('1CPI', '1CPI'), ('2CPI', '2CPI'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=190, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='placebirth',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=190),
        ),
    ]
