# Generated by Django 3.2.8 on 2022-01-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0014_auto_20220110_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='datebirth',
            field=models.DateField(null=True),
        ),
    ]
