# Generated by Django 3.2.8 on 2022-01-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0016_auto_20220110_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='images/user.png', upload_to='images/'),
        ),
    ]
