# Generated by Django 3.2.8 on 2022-01-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0017_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='images/user.png', null=True, upload_to='images/'),
        ),
    ]
