# Generated by Django 3.2.8 on 2022-01-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0018_alter_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('surname', models.CharField(max_length=190)),
                ('email', models.EmailField(max_length=190)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(default='images/user.png', null=True, upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
