# Generated by Django 3.2.8 on 2022-01-18 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0019_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, unique=True)),
                ('address', models.CharField(max_length=190)),
                ('email', models.EmailField(max_length=190)),
                ('phone', models.CharField(max_length=10)),
                ('fax', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('surname', models.CharField(max_length=190)),
                ('email', models.EmailField(max_length=190)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(default='images/user.png', null=True, upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GestionStages.company')),
            ],
        ),
    ]
