# Generated by Django 3.2.8 on 2022-01-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0020_company_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legalstatus',
            field=models.CharField(choices=[('public', 'Publique'), ('private', 'Privée'), ('semi-public', 'Semi-Publique')], max_length=15, null=True),
        ),
    ]
