# Generated by Django 3.2.8 on 2022-01-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0021_company_legalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
