# Generated by Django 3.2.8 on 2022-01-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0022_auto_20220118_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='legalstatus',
            field=models.CharField(blank=True, choices=[('public', 'Publique'), ('private', 'Privée'), ('semi-public', 'Semi-Publique')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
    ]
