# Generated by Django 3.2.8 on 2022-01-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0023_auto_20220118_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='photo',
        ),
    ]
