# Generated by Django 3.2.8 on 2022-01-19 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0024_remove_promoter_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1CPI', '1CPI'), ('1CS', '1CS'), ('3CS', '3CS')], max_length=190)),
                ('titre', models.CharField(max_length=190)),
                ('description', models.CharField(max_length=1000)),
                ('datedeb', models.DateField()),
                ('datefin', models.DateField()),
                ('convention', models.FileField(null=True, upload_to='files/')),
                ('rapport', models.FileField(null=True, upload_to='files/')),
                ('fichesuiv1', models.FileField(null=True, upload_to='files/')),
                ('fichesuiv2', models.FileField(null=True, upload_to='files/')),
                ('fichesuiv3', models.FileField(null=True, upload_to='files/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GestionStages.company')),
                ('students', models.ManyToManyField(to='GestionStages.Student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionStages.teacher')),
            ],
        ),
    ]
