# Generated by Django 3.2.8 on 2022-01-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0025_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='promoter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionStages.promoter'),
        ),
        migrations.AddField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('inprogress', 'En Cours'), ('out', 'Annulé'), ('valid', 'Validé'), ('deadline', 'Délai Non Respecté')], default='inprogress', max_length=190),
        ),
    ]
