# Generated by Django 3.2.8 on 2022-01-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0028_alter_stage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='legalstatus',
            field=models.CharField(blank=True, choices=[('Publique', 'public'), ('Privée', 'private'), ('Semi-Publique', 'semi-public')], max_length=15, null=True),
        ),
    ]
