# Generated by Django 3.2.8 on 2022-01-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0029_alter_company_legalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='legalstatus',
            field=models.CharField(blank=True, choices=[('public', 'Publique'), ('private', 'Privée'), ('semi-public', 'Semi-Publique')], max_length=15, null=True),
        ),
    ]
