# Generated by Django 3.2.8 on 2022-01-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0032_auto_20220119_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='company',
        ),
    ]
