# Generated by Django 3.2.8 on 2022-01-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0033_remove_stage_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionStages.company'),
            preserve_default=False,
        ),
    ]
