# Generated by Django 3.2.8 on 2022-01-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0034_stage_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(max_length=190),
        ),
    ]
