# Generated by Django 3.2.8 on 2022-01-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0035_alter_stage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(max_length=4000),
        ),
    ]
