# Generated by Django 3.2.8 on 2022-01-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0036_alter_stage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='titre',
            field=models.CharField(max_length=4000),
        ),
    ]
