# Generated by Django 3.2.8 on 2022-01-21 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GestionStages', '0038_alter_stage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('En Cours', 'En Cours'), ('Annulé', 'Annulé'), ('Validé', 'Validé'), ('Délai Non Respecté', 'Délai Non Respecté')], default='inprogress', max_length=190),
        ),
    ]
