# Generated by Django 3.2.8 on 2022-01-22 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStages', '0041_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionStages.company'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionStages.company'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionStages.promoter'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionStages.teacher'),
        ),
    ]
